#!/usr/bin/env python3
"""Generate 002_seed_data.sql from parsed JSON files."""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARSED = os.path.join(ROOT, "data", "parsed")
OUT = os.path.join(ROOT, "supabase", "migrations", "002_seed_data.sql")


def escape_sql(s: str) -> str:
    """Escape single quotes for SQL strings."""
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_bool(b: bool) -> str:
    return "TRUE" if b else "FALSE"


def sql_array(arr: list) -> str:
    """Convert a Python list to a PostgreSQL array literal."""
    if not arr:
        return "'{}'::TEXT[]"
    escaped = [s.replace("'", "''") for s in arr]
    return "'{" + ",".join(f'"{e}"' for e in escaped) + "}'::TEXT[]"


def sql_jsonb(obj) -> str:
    """Convert a Python object to a JSONB literal."""
    return escape_sql(json.dumps(obj, ensure_ascii=False)) + "::JSONB"


def main():
    lines = []
    lines.append("-- Sentinel Seed Data v1")
    lines.append("-- Auto-generated by scripts/generate_seed.py")
    lines.append("-- Source: NIST AI 100-1, CRI FS AI RMF Guidebook v1.0")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    # ── Taxonomy ──────────────────────────────────────────────
    with open(os.path.join(PARSED, "nist-ai-rmf-taxonomy.json")) as f:
        taxonomy = json.load(f)

    lines.append("-- ============================================================")
    lines.append("-- Functions")
    lines.append("-- ============================================================")
    lines.append("")
    for fn in taxonomy["functions"]:
        lines.append(
            f"INSERT INTO sentinel_functions (id, name, description, is_crosscutting, sort_order) VALUES "
            f"({escape_sql(fn['id'])}, {escape_sql(fn['name'])}, {escape_sql(fn['description'])}, "
            f"{sql_bool(fn['is_crosscutting'])}, {fn['sort_order']});"
        )
    lines.append("")

    lines.append("-- ============================================================")
    lines.append("-- Categories")
    lines.append("-- ============================================================")
    lines.append("")
    for cat in taxonomy["categories"]:
        lines.append(
            f"INSERT INTO sentinel_categories (id, function_id, name, description, sort_order) VALUES "
            f"({escape_sql(cat['id'])}, {escape_sql(cat['function_id'])}, {escape_sql(cat['name'])}, "
            f"{escape_sql(cat['description'])}, {cat['sort_order']});"
        )
    lines.append("")

    lines.append("-- ============================================================")
    lines.append("-- Subcategories")
    lines.append("-- ============================================================")
    lines.append("")
    for sub in taxonomy["subcategories"]:
        actions = sub.get("suggested_actions", [])
        lines.append(
            f"INSERT INTO sentinel_subcategories (id, category_id, name, description, suggested_actions, sort_order) VALUES "
            f"({escape_sql(sub['id'])}, {escape_sql(sub['category_id'])}, {escape_sql(sub['name'])}, "
            f"{escape_sql(sub['description'])}, {sql_jsonb(actions)}, {sub['sort_order']});"
        )
    lines.append("")

    lines.append("-- ============================================================")
    lines.append("-- Trustworthiness Characteristics")
    lines.append("-- ============================================================")
    lines.append("")
    for tc in taxonomy["trustworthy_characteristics"]:
        lines.append(
            f"INSERT INTO sentinel_trustworthy_characteristics (id, name, description, is_foundational, is_crosscutting, sort_order) VALUES "
            f"({escape_sql(tc['id'])}, {escape_sql(tc['name'])}, {escape_sql(tc['description'])}, "
            f"{sql_bool(tc['is_foundational'])}, {sql_bool(tc['is_crosscutting'])}, {tc['sort_order']});"
        )
    lines.append("")

    # ── Controls ──────────────────────────────────────────────
    with open(os.path.join(PARSED, "fs-ai-rmf-controls.json")) as f:
        controls_data = json.load(f)

    lines.append("-- ============================================================")
    lines.append("-- FS AI RMF Control Objectives (230)")
    lines.append("-- ============================================================")
    lines.append("")
    for ctrl in controls_data["controls"]:
        lines.append(
            f"INSERT INTO sentinel_control_objectives "
            f"(id, subcategory_id, objective_text, implementation_guidance, adoption_stages, "
            f"risk_statement, trustworthy_principle, sort_order) VALUES "
            f"({escape_sql(ctrl['id'])}, {escape_sql(ctrl['subcategory_id'])}, "
            f"{escape_sql(ctrl['objective_text'])}, {escape_sql(ctrl.get('implementation_guidance'))}, "
            f"{sql_array(ctrl['adoption_stages'])}, {escape_sql(ctrl.get('risk_statement'))}, "
            f"{escape_sql(ctrl.get('trustworthy_principle'))}, {ctrl['sort_order']});"
        )
    lines.append("")

    # ── Glossary ──────────────────────────────────────────────
    with open(os.path.join(PARSED, "glossary.json")) as f:
        glossary = json.load(f)

    lines.append("-- ============================================================")
    lines.append("-- Glossary (82 terms)")
    lines.append("-- ============================================================")
    lines.append("")
    for term in glossary["terms"]:
        related = term.get("related_terms", [])
        lines.append(
            f"INSERT INTO sentinel_glossary (term, definition, source, related_terms, category) VALUES "
            f"({escape_sql(term['term'])}, {escape_sql(term['definition'])}, "
            f"{escape_sql(term.get('source'))}, {sql_array(related)}, "
            f"{escape_sql(term.get('category'))});"
        )
    lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUT}")
    print(f"  Functions: {len(taxonomy['functions'])}")
    print(f"  Categories: {len(taxonomy['categories'])}")
    print(f"  Subcategories: {len(taxonomy['subcategories'])}")
    print(f"  Trustworthiness: {len(taxonomy['trustworthy_characteristics'])}")
    print(f"  Controls: {len(controls_data['controls'])}")
    print(f"  Glossary: {len(glossary['terms'])}")
    total = (
        len(taxonomy["functions"])
        + len(taxonomy["categories"])
        + len(taxonomy["subcategories"])
        + len(taxonomy["trustworthy_characteristics"])
        + len(controls_data["controls"])
        + len(glossary["terms"])
    )
    print(f"  Total rows: {total}")


if __name__ == "__main__":
    main()
